name: build

on: push

jobs:
  build:
    name: build
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3

    - uses: msys2/setup-msys2@v2
      with:
        update: true

    - name: Build
      shell: msys2 {0}
      run: >-
        ./build --mode=gcc-6.5.0 --buildroot=/c/buildroot --jobs=4 --rev=0 --rt-version=v10.0.0 --threads=posix --exceptions=seh --arch=x86_64 --bin-compress --enable-languages=c,c++ --logviewer-command=cat --no-bootstrap --cflags=-Wno-error

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        path: c:/buildroot/archives/x86_64-6.5.0-release-posix-seh-rt_v10.0.0-rev0.7z
        name: x86_64-6.5.0-release-posix-seh-rt_v10.0.0-rev0.7z